### ISSUE TITLE
Hi, Where is your code result?

### ISSUE THREAD

**Issue by li1997522** [joanlyq/quick-stitching-for-drone#1]
I run this code, but I dont find the final stitching pic? So here is the running result in pycharm , This code is already done or I miss some package?
```
D:\ProgramData\Anaconda3\envs\python36\python.exe D:/CHENGXU/pinjie/quick-stitching-for-drone-main/quick-stitching-for-drone-main/main.py
========================================
2022-01-19 17:27:54 - Start Program
========================================

CRS : EPSG:32755; Refrative Index: 1.0

Starting Thread-0


Starting Thread-1


Starting Thread-2


Starting Thread-3


Starting Thread-4

ERROR 1: Deleting datasets/outputs/DJI_0001.tif failed:
Permission denied
ERROR 1: _TIFFPartialReadStripArray:Cannot read offset/size for strile around ~0
ERROR 1: _TIFFPartialReadStripArray:Cannot read offset/size for strile around ~0
ERROR 1: datasets/outputs/DJI_0001.tif, band 1: IReadBlock failed at X offset 0, Y offset 0: _TIFFPartialReadStripArray:Cannot read offset/size for strile around ~0
successfully add projection CRS: EPSG:32755 to datasets/images/DJI_0001.JPG
TFW file created for datasets/images/DJI_0001.JPG

Exiting Thread-0

�ļ�����Ŀ¼�������﷨����ȷ��
ERROR 1: Deleting datasets/outputs/DJI_0005.tif failed:
Permission denied
ERROR 1: _TIFFPartialReadStripArray:Cannot read offset/size for strile around ~0
ERROR 1: _TIFFPartialReadStripArray:Cannot read offset/size for strile around ~0
ERROR 1: datasets/outputs/DJI_0005.tif, band 1: IReadBlock failed at X offset 0, Y offset 0: _TIFFPartialReadStripArray:Cannot read offset/size for strile around ~0
ERROR 1: Deleting datasets/outputs/DJI_0004.tif failed:
Permission denied
ERROR 1: _TIFFPartialReadStripArray:Cannot read offset/size for strile around ~0
ERROR 1: _TIFFPartialReadStripArray:Cannot read offset/size for strile around ~0
ERROR 1: datasets/outputs/DJI_0004.tif, band 1: IReadBlock failed at X offset 0, Y offset 0: _TIFFPartialReadStripArray:Cannot read offset/size for strile around ~0
successfully add projection CRS: EPSG:32755 to datasets/images/DJI_0005.JPG
successfully add projection CRS: EPSG:32755 to datasets/images/DJI_0004.JPG
TFW file created for datasets/images/DJI_0005.JPG
�ļ�����Ŀ¼�������﷨����ȷ��
�ļ�����Ŀ¼�������﷨����ȷ��
ERROR 1: Deleting datasets/outputs/DJI_0003.tif failed:
Permission denied
ERROR 1: _TIFFPartialReadStripArray:Cannot read offset/size for strile around ~0
ERROR 1: _TIFFPartialReadStripArray:Cannot read offset/size for strile around ~0
ERROR 1: datasets/outputs/DJI_0003.tif, band 1: IReadBlock failed at X offset 0, Y offset 0: _TIFFPartialReadStripArray:Cannot read offset/size for strile around ~0

Exiting Thread-4

TFW file created for datasets/images/DJI_0004.JPG

Exiting Thread-3

�ļ�����Ŀ¼�������﷨����ȷ��
ERROR 1: Deleting datasets/outputs/DJI_0002.tif failed:
Permission denied
successfully add projection CRS: EPSG:32755 to datasets/images/DJI_0003.JPG
TFW file created for datasets/images/DJI_0003.JPG

Exiting Thread-2

ERROR 1: _TIFFPartialReadStripArray:Cannot read offset/size for strile around ~0
ERROR 1: _TIFFPartialReadStripArray:Cannot read offset/size for strile around ~0
ERROR 1: datasets/outputs/DJI_0002.tif, band 1: IReadBlock failed at X offset 0, Y offset 0: _TIFFPartialReadStripArray:Cannot read offset/size for strile around ~0
successfully add projection CRS: EPSG:32755 to datasets/images/DJI_0002.JPG
TFW file created for datasets/images/DJI_0002.JPG

Exiting Thread-1

�ļ�����Ŀ¼�������﷨����ȷ��
ϵͳ�Ҳ���ָ����·����
Merge failed, try again
Create overview failed, try again
MOSAIC DONE!
========================================
2022-01-19 17:27:57 - End Program
Elapsed time: 0:00:03.529954
========================================

ϵͳ�Ҳ���ָ����·����

Process finished with exit code 0

```

**Comment by joanlyq** [comment]
it should be in the dataset folder, but I'm not sure what is happening in your case, you've got a lot of error with `permission denied`. It might be some setting with your PC, like "run as admin"?

**Comment by li1997522** [comment]
Thanks for your help! I think the problem maybe is the package version. I try to use your environment file , but the yml file is not work. So I change to python3.8 , I find its still wrong. 
`D:\ProgramData\Anaconda3\envs\python38\python.exe D:/CHENGXU/pinjie/quick-stitching-for-drone-main/quick-stitching-for-drone-main/main.py
========================================
2022-01-21 18:57:31 - Start Program
========================================

CRS : EPSG:32755; Refrative Index: 1.0
5

Starting Thread-0

5

Starting Thread-1

5

Starting Thread-2

5

Starting Thread-3
5


Starting Thread-4

Merge failed, try again
Exception in thread Thread-0:
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\python38\lib\threading.py", line 932, in _bootstrap_inner
Exception in thread Thread-1:
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "D:\CHENGXU\pinjie\quick-stitching-for-drone-main\quick-stitching-for-drone-main\mosaic.py", line 71, in run
    self.run()
  File "D:\CHENGXU\pinjie\quick-stitching-for-drone-main\quick-stitching-for-drone-main\mosaic.py", line 71, in run
Exception in thread Thread-2:
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\python38\lib\threading.py", line 932, in _bootstrap_inner
    self.georeferenceImage()
  File "D:\CHENGXU\pinjie\quick-stitching-for-drone-main\quick-stitching-for-drone-main\mosaic.py", line 29, in georeferenceImage
    self.georeferenceImage()
  File "D:\CHENGXU\pinjie\quick-stitching-for-drone-main\quick-stitching-for-drone-main\mosaic.py", line 29, in georeferenceImage
Exception in thread Thread-3:
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\python38\lib\threading.py", line 932, in _bootstrap_inner
Exception in thread Thread-4:
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
    print("tiff generated from {} exists, skip georeferencing and creating twf file".format(self.dataMatrix[i][0]))
NameError: name 'i' is not defined  File "D:\CHENGXU\pinjie\quick-stitching-for-drone-main\quick-stitching-for-drone-main\mosaic.py", line 71, in run

    print("tiff generated from {} exists, skip georeferencing and creating twf file".format(self.dataMatrix[i][0]))
NameError: name 'i' is not defined
    self.georeferenceImage()
  File "D:\CHENGXU\pinjie\quick-stitching-for-drone-main\quick-stitching-for-drone-main\mosaic.py", line 29, in georeferenceImage
    self.run()
  File "D:\CHENGXU\pinjie\quick-stitching-for-drone-main\quick-stitching-for-drone-main\mosaic.py", line 71, in run
    self.run()
  File "D:\CHENGXU\pinjie\quick-stitching-for-drone-main\quick-stitching-for-drone-main\mosaic.py", line 71, in run
    print("tiff generated from {} exists, skip georeferencing and creating twf file".format(self.dataMatrix[i][0]))
NameError: name 'i' is not defined
    self.georeferenceImage()
  File "D:\CHENGXU\pinjie\quick-stitching-for-drone-main\quick-stitching-for-drone-main\mosaic.py", line 29, in georeferenceImage
    self.georeferenceImage()
  File "D:\CHENGXU\pinjie\quick-stitching-for-drone-main\quick-stitching-for-drone-main\mosaic.py", line 29, in georeferenceImage
    print("tiff generated from {} exists, skip georeferencing and creating twf file".format(self.dataMatrix[i][0]))
NameError: name 'i' is not defined
    print("tiff generated from {} exists, skip georeferencing and creating twf file".format(self.dataMatrix[i][0]))
NameError: name 'i' is not defined
ϵͳ�Ҳ���ָ����·����
Create overview failed, try again
========================================
2022-01-21 18:57:33 - End Program
Elapsed time: 0:00:01.947788
========================================

ϵͳ�Ҳ���ָ����·����

Process finished with exit code 0`
By the way , may I see your sample result ?  Thanks again！

**Comment by li1997522** [comment]
Thanks for your help! I think the problem maybe is the package version. I try to use your environment file , but the yml file is not work. So I change to python3.8 , I find its still wrong. By the way , may I see your sample result ? Thanks again！

`D:\ProgramData\Anaconda3\envs\python38\python.exe D:/CHENGXU/pinjie/quick-stitching-for-drone-main/quick-stitching-for-drone-main/main.py
2022-01-21 18:57:31 - Start Program
CRS : EPSG:32755; Refrative Index: 1.0
5

Starting Thread-0

5

Starting Thread-1

5

Starting Thread-2

5

Starting Thread-3
5

Starting Thread-4

Merge failed, try again
Exception in thread Thread-0:
Traceback (most recent call last):
File "D:\ProgramData\Anaconda3\envs\python38\lib\threading.py", line 932, in _bootstrap_inner
Exception in thread Thread-1:
Traceback (most recent call last):
File "D:\ProgramData\Anaconda3\envs\python38\lib\threading.py", line 932, in _bootstrap_inner
self.run()
File "D:\CHENGXU\pinjie\quick-stitching-for-drone-main\quick-stitching-for-drone-main\mosaic.py", line 71, in run
self.run()
File "D:\CHENGXU\pinjie\quick-stitching-for-drone-main\quick-stitching-for-drone-main\mosaic.py", line 71, in run
Exception in thread Thread-2:
Traceback (most recent call last):
File "D:\ProgramData\Anaconda3\envs\python38\lib\threading.py", line 932, in _bootstrap_inner
self.georeferenceImage()
File "D:\CHENGXU\pinjie\quick-stitching-for-drone-main\quick-stitching-for-drone-main\mosaic.py", line 29, in georeferenceImage
self.georeferenceImage()
File "D:\CHENGXU\pinjie\quick-stitching-for-drone-main\quick-stitching-for-drone-main\mosaic.py", line 29, in georeferenceImage
Exception in thread Thread-3:
Traceback (most recent call last):
File "D:\ProgramData\Anaconda3\envs\python38\lib\threading.py", line 932, in _bootstrap_inner
Exception in thread Thread-4:
Traceback (most recent call last):
File "D:\ProgramData\Anaconda3\envs\python38\lib\threading.py", line 932, in _bootstrap_inner
self.run()
print("tiff generated from {} exists, skip georeferencing and creating twf file".format(self.dataMatrix[i][0]))
NameError: name 'i' is not defined File "D:\CHENGXU\pinjie\quick-stitching-for-drone-main\quick-stitching-for-drone-main\mosaic.py", line 71, in run

print("tiff generated from {} exists, skip georeferencing and creating twf file".format(self.dataMatrix[i][0]))
NameError: name 'i' is not defined
self.georeferenceImage()
File "D:\CHENGXU\pinjie\quick-stitching-for-drone-main\quick-stitching-for-drone-main\mosaic.py", line 29, in georeferenceImage
self.run()
File "D:\CHENGXU\pinjie\quick-stitching-for-drone-main\quick-stitching-for-drone-main\mosaic.py", line 71, in run
self.run()
File "D:\CHENGXU\pinjie\quick-stitching-for-drone-main\quick-stitching-for-drone-main\mosaic.py", line 71, in run
print("tiff generated from {} exists, skip georeferencing and creating twf file".format(self.dataMatrix[i][0]))
NameError: name 'i' is not defined
self.georeferenceImage()
File "D:\CHENGXU\pinjie\quick-stitching-for-drone-main\quick-stitching-for-drone-main\mosaic.py", line 29, in georeferenceImage
self.georeferenceImage()
File "D:\CHENGXU\pinjie\quick-stitching-for-drone-main\quick-stitching-for-drone-main\mosaic.py", line 29, in georeferenceImage
print("tiff generated from {} exists, skip georeferencing and creating twf file".format(self.dataMatrix[i][0]))
NameError: name 'i' is not defined
print("tiff generated from {} exists, skip georeferencing and creating twf file".format(self.dataMatrix[i][0]))
NameError: name 'i' is not defined
ϵͳ�Ҳ���ָ����·����
Create overview failed, try again
2022-01-21 18:57:33 - End Program
Elapsed time: 0:00:01.947788
ϵͳ�Ҳ���ָ����·����

Process finished with exit code 0`

**Comment by joanlyq** [comment]
Were you using the main branch or windows branch? The main branch is for mac and linux, not really compatible with windows OS.
